export type Property = {
  id: string;
  slug: string;
  title: string;
  city: string;
  state: "MD" | "DC" | "VA";
  rent: number;
  beds: number;
  baths: number;
  sqft: number;
  image: string;
  gallery: string[];
  tags: ("NEW" | "MOVE-IN READY" | "PET FRIENDLY")[];
  description: string;
  features: string[];
};

const img = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1200&q=75`;

export const properties: Property[] = [
  {
    id: "APM-001",
    slug: "modern-townhome-bowie",
    title: "Modern Townhome – Bowie",
    city: "Bowie, MD",
    state: "MD",
    rent: 2450,
    beds: 3,
    baths: 2.5,
    sqft: 1780,
    image: img("photo-1568605114967-8130f3a36994"),
    gallery: [img("photo-1560448204-e02f11c3d0e2"), img("photo-1600585154340-be6161a56a0c")],
    tags: ["NEW", "MOVE-IN READY"],
    description:
      "Bright, spacious townhome in a quiet Bowie community. Open-concept main level, modern kitchen with stainless appliances, and a private patio.",
    features: ["Attached garage", "Stainless appliances", "In-unit laundry", "Central A/C"],
  },
  {
    id: "APM-002",
    slug: "luxury-apartment-silver-spring",
    title: "Luxury Apartment – Silver Spring",
    city: "Silver Spring, MD",
    state: "MD",
    rent: 2195,
    beds: 2,
    baths: 2,
    sqft: 1120,
    image: img("photo-1522708323590-d24dbb6b0267"),
    gallery: [img("photo-1502672260266-1c1ef2d93688")],
    tags: ["MOVE-IN READY", "PET FRIENDLY"],
    description:
      "Upscale apartment minutes from downtown Silver Spring. Floor-to-ceiling windows, quartz counters, and a fitness center on-site.",
    features: ["Quartz counters", "Concierge", "Fitness center", "Rooftop lounge"],
  },
  {
    id: "APM-003",
    slug: "family-home-baltimore-county",
    title: "Family Home – Baltimore County",
    city: "Baltimore County, MD",
    state: "MD",
    rent: 2895,
    beds: 4,
    baths: 3,
    sqft: 2340,
    image: img("photo-1600596542815-ffad4c1539a9"),
    gallery: [img("photo-1600607687939-ce8a6c25118c")],
    tags: ["NEW", "PET FRIENDLY"],
    description:
      "Roomy single-family home on a quiet street. Fenced backyard, finished basement, and a two-car garage.",
    features: ["Fenced yard", "Finished basement", "2-car garage", "Fireplace"],
  },
  {
    id: "APM-004",
    slug: "pet-friendly-unit-hyattsville",
    title: "Pet-Friendly Unit – Hyattsville",
    city: "Hyattsville, MD",
    state: "MD",
    rent: 1750,
    beds: 2,
    baths: 1,
    sqft: 940,
    image: img("photo-1580587771525-78b9dba3b914"),
    gallery: [img("photo-1600566753190-17f0baa2a6c3")],
    tags: ["PET FRIENDLY", "MOVE-IN READY"],
    description:
      "Charming ground-floor unit welcoming pets. Steps from cafés, transit, and parks.",
    features: ["Pet-friendly", "Hardwood floors", "Dishwasher", "Assigned parking"],
  },
  {
    id: "APM-005",
    slug: "downtown-loft-washington-dc",
    title: "Downtown Loft – Washington DC",
    city: "Washington, DC",
    state: "DC",
    rent: 2750,
    beds: 1,
    baths: 1,
    sqft: 860,
    image: img("photo-1522156373667-4c7234bbd804"),
    gallery: [img("photo-1494203484021-3c454daf695d")],
    tags: ["NEW"],
    description:
      "Modern loft in the heart of DC. Exposed brick, industrial lighting, and walkable to Metro.",
    features: ["Exposed brick", "High ceilings", "Metro access", "Rooftop deck"],
  },
  {
    id: "APM-006",
    slug: "arlington-condo-va",
    title: "Arlington Condo – Virginia",
    city: "Arlington, VA",
    state: "VA",
    rent: 2350,
    beds: 2,
    baths: 2,
    sqft: 1080,
    image: img("photo-1512917774080-9991f1c4c750"),
    gallery: [img("photo-1600585154526-990dced4db0d")],
    tags: ["MOVE-IN READY"],
    description:
      "Well-appointed condo minutes from the Pentagon and DC. Building amenities include pool and 24/7 concierge.",
    features: ["Pool", "Concierge", "Balcony", "In-unit W/D"],
  },
  {
    id: "APM-007",
    slug: "garden-apartment-college-park",
    title: "Garden Apartment – College Park",
    city: "College Park, MD",
    state: "MD",
    rent: 1650,
    beds: 2,
    baths: 1,
    sqft: 910,
    image: img("photo-1493809842364-78817add7ffb"),
    gallery: [img("photo-1502005229762-cf1b2da7c5d6")],
    tags: ["PET FRIENDLY"],
    description:
      "Quiet garden-style apartment near the University of Maryland. Ideal for students and young professionals.",
    features: ["Utilities included", "Pet-friendly", "On-site laundry", "Bike storage"],
  },
  {
    id: "APM-008",
    slug: "renovated-rowhome-baltimore",
    title: "Renovated Rowhome – Baltimore",
    city: "Baltimore, MD",
    state: "MD",
    rent: 1995,
    beds: 3,
    baths: 2,
    sqft: 1560,
    image: img("photo-1449844908441-8829872d2607"),
    gallery: [img("photo-1523217582562-09d0def993a6")],
    tags: ["NEW", "MOVE-IN READY"],
    description:
      "Fully renovated rowhome with modern kitchen, exposed brick, and a private roof deck.",
    features: ["Roof deck", "Renovated kitchen", "Exposed brick", "Central A/C"],
  },
  {
    id: "APM-009",
    slug: "single-family-alexandria",
    title: "Single-Family Home – Alexandria",
    city: "Alexandria, VA",
    state: "VA",
    rent: 3200,
    beds: 4,
    baths: 3,
    sqft: 2450,
    image: img("photo-1564013799919-ab600027ffc6"),
    gallery: [img("photo-1600585154363-67eb9e2e2099")],
    tags: ["NEW", "PET FRIENDLY"],
    description:
      "Elegant single-family home in a friendly Alexandria neighborhood. Large kitchen, formal dining, and a landscaped yard.",
    features: ["Landscaped yard", "2-car garage", "Home office", "Formal dining"],
  },
  {
    id: "APM-010",
    slug: "studio-apartment-dupont",
    title: "Studio Apartment – Dupont Circle",
    city: "Washington, DC",
    state: "DC",
    rent: 1850,
    beds: 0,
    baths: 1,
    sqft: 540,
    image: img("photo-1502672023488-70e25813eb80"),
    gallery: [img("photo-1560448075-bb485b067938")],
    tags: ["MOVE-IN READY"],
    description:
      "Efficient studio in one of DC's most walkable neighborhoods. Steps from restaurants, shops, and Metro.",
    features: ["Walk to Metro", "All utilities included", "Doorman", "Bike room"],
  },
  {
    id: "APM-011",
    slug: "townhouse-frederick",
    title: "Townhouse – Frederick",
    city: "Frederick, MD",
    state: "MD",
    rent: 2100,
    beds: 3,
    baths: 2.5,
    sqft: 1650,
    image: img("photo-1570129477492-45c003edd2be"),
    gallery: [img("photo-1600566753086-00f18fe6ba68")],
    tags: ["PET FRIENDLY", "MOVE-IN READY"],
    description:
      "Bright end-unit townhouse with a two-story great room, updated kitchen, and a private deck backing to trees.",
    features: ["End unit", "Private deck", "1-car garage", "Updated kitchen"],
  },
  {
    id: "APM-012",
    slug: "cozy-condo-rockville",
    title: "Cozy Condo – Rockville",
    city: "Rockville, MD",
    state: "MD",
    rent: 1795,
    beds: 1,
    baths: 1,
    sqft: 720,
    image: img("photo-1484154218962-a197022b5858"),
    gallery: [img("photo-1560185008-b033106af5c3")],
    tags: ["MOVE-IN READY"],
    description:
      "Well-maintained condo near Rockville Town Center. Pool, gym, and easy Metro access.",
    features: ["Pool", "Gym", "Balcony", "Reserved parking"],
  },
  {
    id: "APM-013",
    slug: "family-home-fairfax",
    title: "Family Home – Fairfax",
    city: "Fairfax, VA",
    state: "VA",
    rent: 3050,
    beds: 4,
    baths: 3,
    sqft: 2280,
    image: img("photo-1512917774080-9991f1c4c750"),
    gallery: [img("photo-1600585154526-990dced4db0d")],
    tags: ["NEW"],
    description:
      "Classic colonial in a top school district. Updated throughout with a spacious backyard.",
    features: ["Top schools", "Backyard", "2-car garage", "New HVAC"],
  },
  {
    id: "APM-014",
    slug: "modern-apartment-bethesda",
    title: "Modern Apartment – Bethesda",
    city: "Bethesda, MD",
    state: "MD",
    rent: 2550,
    beds: 2,
    baths: 2,
    sqft: 1150,
    image: img("photo-1502672260266-1c1ef2d93688"),
    gallery: [img("photo-1616486338812-3dadae4b4ace")],
    tags: ["NEW", "MOVE-IN READY"],
    description:
      "Sleek apartment in the heart of Bethesda with premium finishes and rooftop amenities.",
    features: ["Rooftop pool", "Concierge", "Smart home", "EV charging"],
  },
  {
    id: "APM-015",
    slug: "spacious-home-laurel",
    title: "Spacious Home – Laurel",
    city: "Laurel, MD",
    state: "MD",
    rent: 2650,
    beds: 4,
    baths: 2.5,
    sqft: 2100,
    image: img("photo-1600566753376-12c8ab7fb75b"),
    gallery: [img("photo-1600585154340-be6161a56a0c")],
    tags: ["PET FRIENDLY", "MOVE-IN READY"],
    description:
      "Roomy home with generous living areas, a large kitchen, and a fenced backyard perfect for families.",
    features: ["Fenced yard", "Eat-in kitchen", "Basement storage", "Driveway parking"],
  },
  {
    id: "APM-016",
    slug: "urban-flat-navy-yard",
    title: "Urban Flat – Navy Yard",
    city: "Washington, DC",
    state: "DC",
    rent: 2450,
    beds: 1,
    baths: 1,
    sqft: 780,
    image: img("photo-1560448204-603b3fc33ddc"),
    gallery: [img("photo-1522708323590-d24dbb6b0267")],
    tags: ["NEW"],
    description:
      "Contemporary flat in the vibrant Navy Yard neighborhood. Walk to the waterfront, Nats Park, and Metro.",
    features: ["Waterfront steps away", "Concierge", "Pool", "Pet spa"],
  },
];

export const featured = properties.slice(0, 6);
export const getProperty = (slug: string) => properties.find((p) => p.slug === slug);
